GetMem(fcl_lerp_factor, sizeof(TLerpTag) * 10);

fcl_lerp_factor[0].r:=0;
fcl_lerp_factor[0].g:=0;
fcl_lerp_factor[0].b:=0;
fcl_lerp_factor[0].a:=0;
fcl_lerp_factor[0].llength:=64;


fcl_lerp_factor[1].r:=1;
fcl_lerp_factor[1].g:=0;
fcl_lerp_factor[1].b:=0;
fcl_lerp_factor[1].a:=0;
fcl_lerp_factor[1].llength:=64;

fcl_lerp_factor[2].r:=1;
fcl_lerp_factor[2].g:=1;
fcl_lerp_factor[2].b:=0;
fcl_lerp_factor[2].a:=0;
fcl_lerp_factor[2].llength:=64;


fcl_lerp_factor[3].r:=0;
fcl_lerp_factor[3].g:=1;
fcl_lerp_factor[3].b:=0;
fcl_lerp_factor[3].a:=0;
fcl_lerp_factor[3].llength:=64;

fcl_lerp_factor[4].r:=0;
fcl_lerp_factor[4].g:=1;
fcl_lerp_factor[4].b:=1;
fcl_lerp_factor[4].a:=0;
fcl_lerp_factor[4].llength:=64;


fcl_lerp_factor[5].r:=0;
fcl_lerp_factor[5].g:=0;
fcl_lerp_factor[5].b:=1;
fcl_lerp_factor[5].a:=0;
fcl_lerp_factor[5].llength:=64;


fcl_lerp_factor[6].r:=1;
fcl_lerp_factor[6].g:=0;
fcl_lerp_factor[6].b:=1;
fcl_lerp_factor[6].a:=0;
fcl_lerp_factor[6].llength:=64;


fcl_lerp_factor[7].r:=1;
fcl_lerp_factor[7].g:=1;
fcl_lerp_factor[7].b:=1;
fcl_lerp_factor[7].a:=0;
fcl_lerp_factor[7].llength:=64;


fcl_lerp_factor[8].r:=0;
fcl_lerp_factor[8].g:=0;
fcl_lerp_factor[8].b:=0;
fcl_lerp_factor[8].a:=0;
fcl_lerp_factor[8].llength:=5;


fcl_lerp_factor[9].r:=0;
fcl_lerp_factor[9].g:=0;
fcl_lerp_factor[9].b:=0;
fcl_lerp_factor[9].a:=0;
fcl_lerp_factor[9].llength:=64;

fcl_lerp_factor_len := 10;
