//@referenced by (1): fractalito;
regexpr in 'D:\dev\svn\pas\lib\common\pcre\RegExpr.pas',


//dependity tree:
//	[+]-[+]-[FRACTALITO] [15 references]
//	 |	 |
//	 |	[-]-[windows] @1
//	 |	[-]-[messages] @1
//	 |	[-]-[sysutils] @1
//	 |	[-]-[variants] @1
//	 |	[-]-[classes] @1
//	 |	[-]-[graphics] @1
//	 |	[-]-[controls] @1
//	 |	[-]-[forms] @1
//	 |	[-]-[dialogs] @1
//	 |	[-]-[stdctrls] @1
//	 |	[-]-[extctrls] @1
//	 |	[-]-[math] @1
//	 |	[-]-[comctrls] @1
//	 |	[-]-[clipbrd] @1
//	 |	[-]-[regexpr] @1
//	 |
//	[+]-[+]-[REGEXPR] [3 references]
//	 |	 |
//	 |	[-]-[classes] @2
//	 |	[-]-[sysutils] @2
//	 |	[-]-[windows] @2
//	 |